export const portedGames = [
  {
    id: "cuphead", number: "05", name: ["", "CUPHEAD"] as [string, string],
    genre: "Run-and-gun platformer", tagline: "Don't deal with the devil.",
    description: "Hand-drawn worlds, larger-than-life bosses and a jazz-fuelled run-and-gun adventure. Launch the existing browser port straight from the shelf.",
    href: "/play/cuphead", source: "/ports/cuphead/index.html", cta: "PLAY CUPHEAD",
    tone: "orange" as const, cover: "/cuphead-cover-box-art.png", focus: "50% 40%", players: "1–2",
    download: "About 2.1 GB on first launch", creator: "Studio MDHR",
    notice: "Experimental browser port: this large game may run out of browser memory. Desktop recommended.",
    specs: [
      { label: "Game", value: "Existing browser port" },
      { label: "Developer", value: "Studio MDHR" },
      { label: "Controls", value: "Keyboard · see in-game options" },
      { label: "First download", value: "About 2.1 GB · desktop recommended" },
    ],
    features: ["Hand-drawn animation", "Boss battles", "Full-screen player"],
  },
  {
    id: "20-minutes-till-dawn", number: "06", name: ["20 MINUTES", "TILL DAWN"] as [string, string],
    genre: "Survival roguelite", tagline: "Survive the night. Build something devastating.",
    description: "Fight through swarms of eldritch creatures, collect upgrades and turn a lone survivor into a storm of bullets. Launch the existing browser port and take on the night.",
    href: "/play/20-minutes-till-dawn", source: "/ports/20-minutes-till-dawn/index.html", cta: "SURVIVE THE NIGHT",
    tone: "teal" as const, cover: "/20-minutes-cover-box-art.png", focus: "50% 40%", players: "1",
    download: "About 48 MB on first launch", creator: "flanne",
    specs: [
      { label: "Game", value: "Existing browser port" },
      { label: "Developer", value: "flanne" },
      { label: "Controls", value: "Keyboard + mouse · see in-game options" },
      { label: "First download", value: "About 48 MB · desktop recommended" },
    ],
    features: ["Upgrade combinations", "Eldritch hordes", "Full-screen player"],
  },
  {
    id: "hollow-knight", number: "07", name: ["HOLLOW", "KNIGHT"] as [string, string],
    genre: "Metroidvania", tagline: "Descend into the ruined kingdom of Hallownest.",
    description: "Explore twisting caverns, ancient cities and deadly wastes as a tiny knight with a nail and a lot of nerve. Launch the existing browser port straight from the shelf.",
    href: "/play/hollow-knight", source: "/ports/hollow-knight/index.html", cta: "ENTER HALLOWNEST",
    tone: "orange" as const, cover: "/hollow-knight-cover-box-art.png", focus: "50% 40%", players: "1",
    download: "About 860 MB on first launch", creator: "Team Cherry",
    notice: "Experimental browser port: this large game needs plenty of browser memory. Desktop recommended.",
    specs: [
      { label: "Game", value: "Existing browser port" },
      { label: "Developer", value: "Team Cherry" },
      { label: "Controls", value: "Keyboard · see in-game options" },
      { label: "First download", value: "About 860 MB · desktop recommended" },
    ],
    features: ["Hand-drawn kingdom", "Tough-as-nails bosses", "Full-screen player"],
  },
  {
    id: "angry-birds-chrome", number: "08", name: ["ANGRY", "BIRDS"] as [string, string],
    genre: "Physics puzzler", tagline: "Pull back. Let fly. Topple the pigs.",
    description: "Rovio's original slingshot puzzler in its 2011 Chrome edition: fling the flock at wobbly pig fortresses across the classic episodes, plus the Chrome-exclusive levels.",
    href: "/play/angry-birds-chrome", source: "/ports/angry-birds-chrome/index.html", cta: "LAUNCH THE FLOCK",
    tone: "teal" as const, cover: "/angry-birds-chrome-cover-box-art.png", focus: "50% 40%", players: "1",
    download: "About 50 MB on first launch", creator: "Rovio",
    specs: [
      { label: "Game", value: "Existing browser port" },
      { label: "Developer", value: "Rovio Entertainment" },
      { label: "Controls", value: "Mouse or touch · drag to aim" },
      { label: "First download", value: "About 50 MB" },
    ],
    features: ["Classic episodes", "Chrome-exclusive levels", "Full-screen player"],
  },
  {
    id: "angry-birds-epic", number: "09", name: ["ANGRY BIRDS", "EPIC"] as [string, string],
    genre: "Turn-based RPG", tagline: "Swords, spatulas and pigs that need a beating.",
    description: "The flock trades the slingshot for turn-based battles: equip Red and friends with homemade weapons and armour and fight across Piggy Island. A Unity WebGL build of version 3.0.1.",
    href: "/play/angry-birds-epic", source: "/ports/angry-birds-epic/index.html", cta: "GO ON THE QUEST",
    tone: "orange" as const, cover: "/angry-birds-epic-cover-box-art.png", focus: "50% 40%", players: "1",
    download: "About 175 MB on first launch", creator: "Rovio",
    specs: [
      { label: "Game", value: "Existing browser port" },
      { label: "Developer", value: "Rovio Entertainment" },
      { label: "Controls", value: "Mouse or touch · tap to attack" },
      { label: "First download", value: "About 175 MB · desktop recommended" },
    ],
    features: ["Turn-based battles", "Crafting and gear", "Full-screen player"],
  },
  {
    id: "angry-birds-hatchery-island", number: "10", name: ["ANGRY BIRDS", "HATCHERY"] as [string, string],
    genre: "Island builder + slingshot", tagline: "Hatch a flock. Then launch it.",
    description: "A preservation port of Rovio's unreleased 2011 iPad prototype: build nests, hatch and design your own birds on Hatchery Island, then send them at the pigs across 325 recovered levels.",
    href: "/play/angry-birds-hatchery-island", source: "/ports/angry-birds-hatchery-island/index.html", cta: "START HATCHING",
    tone: "teal" as const, cover: "/angry-birds-hatchery-island-cover-box-art.png", focus: "50% 40%", players: "1",
    download: "About 30 MB on first launch", creator: "Rovio (fan preservation)",
    notice: "Work-in-progress preservation port: some original features are still being restored.",
    specs: [
      { label: "Game", value: "Existing browser port" },
      { label: "Developer", value: "Rovio Entertainment · port by tonygamer1515" },
      { label: "Controls", value: "Mouse or touch · drag to pan and aim" },
      { label: "First download", value: "About 30 MB" },
    ],
    features: ["Unreleased prototype", "Hatch your own birds", "325 recovered levels"],
  },
  {
    id: "angry-birds-chrome-flash", number: "11", name: ["ANGRY BIRDS", "CLASSIC"] as [string, string],
    genre: "Physics puzzler", tagline: "The original slingshot, in Flash.",
    description: "The classic grassland levels rebuilt as a Flash game: wooden towers, pigs on every ledge and one slingshot to sort it out. A lighter alternative to the Chrome edition.",
    href: "/play/angry-birds-chrome-flash", source: "/ports/flash/index.html?game=angry-birds-chrome-flash", cta: "PULL THE SLINGSHOT",
    tone: "orange" as const, cover: "/angry-birds-chrome-flash-cover-box-art.png", focus: "50% 40%", players: "1",
    download: "About 15 MB", creator: "Flash fan game",
    notice: "Flash game played through the Ruffle emulator; some effects may differ from the original.",
    specs: [
      { label: "Game", value: "Flash game · Ruffle emulator" },
      { label: "Developer", value: "Unofficial Flash fan game" },
      { label: "Controls", value: "Mouse · drag to aim" },
      { label: "First download", value: "About 15 MB" },
    ],
    features: ["Classic levels", "Flash classic", "Full-screen player"],
  },
  {
    id: "angry-birds-space", number: "12", name: ["ANGRY BIRDS", "SPACE"] as [string, string],
    genre: "Gravity puzzler", tagline: "Fling birds through zero gravity.",
    description: "Launch the flock from tiny planets and curve shots through gravity fields to knock pigs off floating platforms before the clock runs out.",
    href: "/play/angry-birds-space", source: "/ports/flash/index.html?game=angry-birds-space", cta: "LAUNCH INTO ORBIT",
    tone: "teal" as const, cover: "/angry-birds-space-cover-box-art.png", focus: "50% 40%", players: "1",
    download: "About 13 MB", creator: "Flash fan game",
    notice: "Flash game played through the Ruffle emulator; some effects may differ from the original.",
    specs: [
      { label: "Game", value: "Flash game · Ruffle emulator" },
      { label: "Developer", value: "Unofficial Flash fan game" },
      { label: "Controls", value: "Mouse · drag to aim" },
      { label: "First download", value: "About 13 MB" },
    ],
    features: ["Gravity shots", "Timed levels", "Full-screen player"],
  },
  {
    id: "angry-birds-halloween", number: "13", name: ["ANGRY BIRDS", "HALLOWEEN"] as [string, string],
    genre: "Physics puzzler", tagline: "Pumpkins, full moons and pigs hiding in graveyards.",
    description: "A spooky Halloween set of slingshot levels: launch Red, Chuck and Bomb across a moonlit pumpkin patch at pigs hiding in creaky fortresses.",
    href: "/play/angry-birds-halloween", source: "/ports/flash/index.html?game=angry-birds-halloween", cta: "TRICK OR TREAT",
    tone: "orange" as const, cover: "/angry-birds-halloween-cover-box-art.png", focus: "50% 40%", players: "1",
    download: "About 15 MB", creator: "Flash fan game",
    notice: "Flash game played through the Ruffle emulator; some effects may differ from the original.",
    specs: [
      { label: "Game", value: "Flash game · Ruffle emulator" },
      { label: "Developer", value: "Unofficial Flash fan game" },
      { label: "Controls", value: "Mouse · drag to aim" },
      { label: "First download", value: "About 15 MB" },
    ],
    features: ["Halloween levels", "Three bird types", "Full-screen player"],
  },
  {
    id: "cut-the-rope", number: "14", name: ["CUT THE", "ROPE"] as [string, string],
    genre: "Physics puzzler", tagline: "Feed Om Nom the candy. Cut the right rope.",
    description: "The full game: slice ropes, pop bubbles and bounce candy into Om Nom's mouth across every box from Cardboard to Mechanical, plus the Spooky and Steam boxes. Played through Cut the Rope DX, a fan-made browser build of the PC version.",
    href: "/play/cut-the-rope", source: "/ports/cut-the-rope/index.html", cta: "FEED OM NOM",
    tone: "teal" as const, cover: "/cut-the-rope-cover-box-art.png", focus: "50% 40%", players: "1",
    download: "About 45 MB on first launch", creator: "ZeptoLab · Cut the Rope DX",
    notice: "Fan-made browser build of the full game. Press Play once its loading screen finishes.",
    specs: [
      { label: "Game", value: "Fan-made browser build (Cut the Rope DX)" },
      { label: "Developer", value: "ZeptoLab · port by yell0wsuit" },
      { label: "Controls", value: "Mouse or touch · drag to cut" },
      { label: "First download", value: "About 45 MB" },
    ],
    features: ["Every box, Cardboard to Mechanical", "Stars and progress saved", "Full-screen player"],
  },
  {
    id: "helltaker", number: "15", name: ["", "HELLTAKER"] as [string, string],
    genre: "Puzzle adventure", tagline: "A short game about sharply dressed demon girls.",
    description: "Push skeletons, kick boulders and count every step as you descend through Hell to assemble a harem of demon girls. The complete game: chapters I to X plus the EX bonus chapter, all open from chapter select.",
    href: "/play/helltaker", source: "/ports/helltaker/index.html", cta: "DESCEND INTO HELL",
    tone: "orange" as const, cover: "/helltaker-cover-box-art.png", focus: "50% 40%", players: "1",
    download: "About 96 MB on first launch", creator: "vanripper",
    specs: [
      { label: "Game", value: "Existing browser port · full game" },
      { label: "Developer", value: "vanripper" },
      { label: "Controls", value: "Arrow keys / WASD · Enter · R to restart" },
      { label: "First download", value: "About 96 MB · desktop recommended" },
    ],
    features: ["Chapters I–X + EX", "Chapter select", "Full-screen player"],
  },
  {
    id: "zuma-the-lost-treasure", number: "16", name: ["ZUMA", "LOST TREASURE"] as [string, string],
    genre: "Marble shooter", tagline: "Stop the chain before it reaches the skull.",
    description: "Spin the stone frog idol and fire coloured balls into the rolling chain: match three to clear them, set off combos and grab reverse, slow and explosion power-ups before the chain reaches the golden skull.",
    href: "/play/zuma-the-lost-treasure", source: "/ports/flash/index.html?game=zuma-the-lost-treasure", cta: "AWAKEN THE IDOL",
    tone: "teal" as const, cover: "/zuma-the-lost-treasure-cover-box-art.png", focus: "50% 40%", players: "1",
    download: "About 11 MB on first launch", creator: "PopCap",
    notice: "Flash game played through the Ruffle emulator; some effects may differ from the original.",
    specs: [
      { label: "Game", value: "Flash game · Ruffle emulator" },
      { label: "Developer", value: "PopCap Games" },
      { label: "Controls", value: "Mouse · aim and click to fire" },
      { label: "First download", value: "About 11 MB" },
    ],
    features: ["Classic Zuma chains", "Power-up balls", "Full-screen player"],
  },
  {
    id: "hill-climb-racing", number: "17", name: ["HILL CLIMB", "RACING"] as [string, string],
    genre: "Physics driving", tagline: "Gas, brake, and try not to land on your head.",
    description: "Newton Bill's full hill-climbing adventure: drive every vehicle across every stage, collect coins and fuel, and spend them on upgrades. The complete Windows game recompiled to run in the browser.",
    href: "/play/hill-climb-racing", source: "/ports/hill-climb-racing/index.html", cta: "HIT THE GAS",
    tone: "orange" as const, cover: "/hill-climb-racing-cover-box-art.png", focus: "50% 40%", players: "1",
    download: "About 170 MB on first launch", creator: "Fingersoft",
    notice: "Needs Chrome or Edge 137 or newer (WebAssembly JSPI). Other browsers show a message instead of the game.",
    specs: [
      { label: "Game", value: "Existing browser port · full game" },
      { label: "Developer", value: "Fingersoft · port by NotRexed / Truffled" },
      { label: "Controls", value: "Arrow keys / touch · gas and brake" },
      { label: "First download", value: "About 170 MB · Chrome or Edge 137+" },
    ],
    features: ["Every vehicle and stage", "Upgrades and coins", "Full-screen player"],
  },
  {
    id: "sonic-4-episode-1", number: "18", name: ["SONIC THE HEDGEHOG 4", "EPISODE I"] as [string, string],
    genre: "Platformer", tagline: "Picks up right where Sonic & Knuckles left off.",
    description: "Spin Dash and Homing Attack through Splash Hill, Casino Street, Lost Labyrinth and Mad Gear to stop Dr. Eggman. The complete Episode I, ported to the browser with .NET WebAssembly.",
    href: "/play/sonic-4-episode-1", source: "/ports/sonic-4-episode-1/index.html", cta: "GOTTA GO FAST",
    tone: "teal" as const, cover: "/sonic-4-episode-1-cover-box-art.png", focus: "50% 40%", players: "1",
    download: "About 150 MB on first launch", creator: "SEGA · port by wamwoowam",
    notice: "Episode I only: no browser port of Episode II exists yet.",
    specs: [
      { label: "Game", value: "Existing browser port · full game" },
      { label: "Developer", value: "SEGA / Sonic Team · port by wamwoowam" },
      { label: "Controls", value: "Arrow keys + Z / X · gamepad supported" },
      { label: "First download", value: "About 150 MB · desktop recommended" },
    ],
    features: ["All four zones + final boss", "Spin Dash and Homing Attack", "Full-screen player"],
  },
  {
    id: "escape-road", number: "19", name: ["ESCAPE", "ROAD"] as [string, string],
    genre: "Police chase", tagline: "Steal a car. Lose the cops.",
    description: "Grab a car and swerve through endless city traffic while the police, SWAT and helicopters close in. Survive as long as you can and unlock new rides.",
    href: "/play/escape-road", source: "/ports/escape-road/index.html", cta: "START THE CHASE",
    tone: "orange" as const, cover: "/escape-road-cover-box-art.png", focus: "50% 40%", players: "1",
    download: "About 30 MB on first launch", creator: "AzGames",
    notice: "Official AzGames embed: the publisher shows a short ad before play.",
    specs: [
      { label: "Game", value: "Official web game embed" },
      { label: "Developer", value: "AzGames" },
      { label: "Controls", value: "WASD / arrows · touch" },
      { label: "First download", value: "About 30 MB" },
    ],
    features: ["Endless police chase", "Unlockable cars", "Full-screen player"],
  },
  {
    id: "escape-road-2", number: "20", name: ["ESCAPE ROAD", "2"] as [string, string],
    genre: "Police chase", tagline: "Bigger maps, angrier police.",
    description: "The sequel takes the chase to new maps with more cars to unlock, tougher pursuers and longer survival runs.",
    href: "/play/escape-road-2", source: "/ports/escape-road-2/index.html", cta: "START THE CHASE",
    tone: "teal" as const, cover: "/escape-road-2-cover-box-art.png", focus: "50% 40%", players: "1",
    download: "About 30 MB on first launch", creator: "AzGames",
    notice: "Official AzGames embed: the publisher shows a short ad before play.",
    specs: [
      { label: "Game", value: "Official web game embed" },
      { label: "Developer", value: "AzGames" },
      { label: "Controls", value: "WASD / arrows · touch" },
      { label: "First download", value: "About 30 MB" },
    ],
    features: ["Endless police chase", "Unlockable cars", "Full-screen player"],
  },
  {
    id: "escape-road-3", number: "21", name: ["ESCAPE ROAD", "3"] as [string, string],
    genre: "Police chase", tagline: "The chase goes further.",
    description: "The third chase: new cities, new vehicles and an even more relentless police response.",
    href: "/play/escape-road-3", source: "/ports/escape-road-3/index.html", cta: "START THE CHASE",
    tone: "orange" as const, cover: "/escape-road-3-cover-box-art.png", focus: "50% 40%", players: "1",
    download: "About 30 MB on first launch", creator: "AzGames",
    notice: "Official AzGames embed: the publisher shows a short ad before play.",
    specs: [
      { label: "Game", value: "Official web game embed" },
      { label: "Developer", value: "AzGames" },
      { label: "Controls", value: "WASD / arrows · touch" },
      { label: "First download", value: "About 30 MB" },
    ],
    features: ["Endless police chase", "Unlockable cars", "Full-screen player"],
  },
  {
    id: "hobo-1", number: "22", name: ["", "HOBO"] as [string, string],
    genre: "Beat 'em up", tagline: "Brawl through the city as the filthiest fighter alive.",
    description: "Part 1 of the Hobo series: punch, kick, and gross-out special moves through the streets as the toughest hobo around. Original Flash game, every level included.",
    href: "/play/hobo-1", source: "/ports/flash/index.html?game=hobo-1", cta: "START BRAWLING",
    tone: "orange" as const, cover: "/hobo-1-cover-box-art.png", focus: "50% 40%", players: "1",
    download: "About 12 MB on first launch", creator: "Seethru Productions",
    notice: "Flash game played through the Ruffle emulator; some effects may differ from the original.",
    specs: [
      { label: "Game", value: "Flash game · Ruffle emulator" },
      { label: "Developer", value: "Seethru Productions" },
      { label: "Controls", value: "Arrow keys + A / S / D · see in-game help" },
      { label: "First download", value: "About 12 MB" },
    ],
    features: ["Full original game", "Gross-out special moves", "Full-screen player"],
  },
  {
    id: "hobo-2", number: "23", name: ["HOBO 2", "PRISON BRAWL"] as [string, string],
    genre: "Beat 'em up", tagline: "Locked up. Fighting out.",
    description: "Part 2 of the Hobo series: punch, kick, and gross-out special moves through prison brawl as the toughest hobo around. Original Flash game, every level included.",
    href: "/play/hobo-2", source: "/ports/flash/index.html?game=hobo-2", cta: "START BRAWLING",
    tone: "teal" as const, cover: "/hobo-2-cover-box-art.png", focus: "50% 40%", players: "1",
    download: "About 12 MB on first launch", creator: "Seethru Productions",
    notice: "Flash game played through the Ruffle emulator; some effects may differ from the original.",
    specs: [
      { label: "Game", value: "Flash game · Ruffle emulator" },
      { label: "Developer", value: "Seethru Productions" },
      { label: "Controls", value: "Arrow keys + A / S / D · see in-game help" },
      { label: "First download", value: "About 12 MB" },
    ],
    features: ["Full original game", "Gross-out special moves", "Full-screen player"],
  },
  {
    id: "hobo-3", number: "24", name: ["HOBO 3", "WANTED"] as [string, string],
    genre: "Beat 'em up", tagline: "The whole city wants him gone.",
    description: "Part 3 of the Hobo series: punch, kick, and gross-out special moves through wanted as the toughest hobo around. Original Flash game, every level included.",
    href: "/play/hobo-3", source: "/ports/flash/index.html?game=hobo-3", cta: "START BRAWLING",
    tone: "orange" as const, cover: "/hobo-3-cover-box-art.png", focus: "50% 40%", players: "1",
    download: "About 13 MB on first launch", creator: "Seethru Productions",
    notice: "Flash game played through the Ruffle emulator; some effects may differ from the original.",
    specs: [
      { label: "Game", value: "Flash game · Ruffle emulator" },
      { label: "Developer", value: "Seethru Productions" },
      { label: "Controls", value: "Arrow keys + A / S / D · see in-game help" },
      { label: "First download", value: "About 13 MB" },
    ],
    features: ["Full original game", "Gross-out special moves", "Full-screen player"],
  },
  {
    id: "hobo-4", number: "25", name: ["HOBO 4", "TOTAL WAR"] as [string, string],
    genre: "Beat 'em up", tagline: "Hobo takes on the army.",
    description: "Part 4 of the Hobo series: punch, kick, and gross-out special moves through total war as the toughest hobo around. Original Flash game, every level included.",
    href: "/play/hobo-4", source: "/ports/flash/index.html?game=hobo-4", cta: "START BRAWLING",
    tone: "teal" as const, cover: "/hobo-4-cover-box-art.png", focus: "50% 40%", players: "1",
    download: "About 14 MB on first launch", creator: "Seethru Productions",
    notice: "Flash game played through the Ruffle emulator; some effects may differ from the original.",
    specs: [
      { label: "Game", value: "Flash game · Ruffle emulator" },
      { label: "Developer", value: "Seethru Productions" },
      { label: "Controls", value: "Arrow keys + A / S / D · see in-game help" },
      { label: "First download", value: "About 14 MB" },
    ],
    features: ["Full original game", "Gross-out special moves", "Full-screen player"],
  },
  {
    id: "hobo-5", number: "26", name: ["HOBO 5", "SPACE BRAWLS"] as [string, string],
    genre: "Beat 'em up", tagline: "Abducted, and furious about it.",
    description: "Part 5 of the Hobo series: punch, kick, and gross-out special moves through space brawls as the toughest hobo around. Original Flash game, every level included.",
    href: "/play/hobo-5", source: "/ports/flash/index.html?game=hobo-5", cta: "START BRAWLING",
    tone: "orange" as const, cover: "/hobo-5-cover-box-art.png", focus: "50% 40%", players: "1",
    download: "About 15 MB on first launch", creator: "Seethru Productions",
    notice: "Flash game played through the Ruffle emulator; some effects may differ from the original.",
    specs: [
      { label: "Game", value: "Flash game · Ruffle emulator" },
      { label: "Developer", value: "Seethru Productions" },
      { label: "Controls", value: "Arrow keys + A / S / D · see in-game help" },
      { label: "First download", value: "About 15 MB" },
    ],
    features: ["Full original game", "Gross-out special moves", "Full-screen player"],
  },
  {
    id: "hobo-6", number: "27", name: ["HOBO 6", "HELL"] as [string, string],
    genre: "Beat 'em up", tagline: "Fighting through the underworld.",
    description: "Part 6 of the Hobo series: punch, kick, and gross-out special moves through hell as the toughest hobo around. Original Flash game, every level included.",
    href: "/play/hobo-6", source: "/ports/flash/index.html?game=hobo-6", cta: "START BRAWLING",
    tone: "teal" as const, cover: "/hobo-6-cover-box-art.png", focus: "50% 40%", players: "1",
    download: "About 14 MB on first launch", creator: "Seethru Productions",
    notice: "Flash game played through the Ruffle emulator; some effects may differ from the original.",
    specs: [
      { label: "Game", value: "Flash game · Ruffle emulator" },
      { label: "Developer", value: "Seethru Productions" },
      { label: "Controls", value: "Arrow keys + A / S / D · see in-game help" },
      { label: "First download", value: "About 14 MB" },
    ],
    features: ["Full original game", "Gross-out special moves", "Full-screen player"],
  },
  {
    id: "hobo-7", number: "28", name: ["HOBO 7", "HEAVEN"] as [string, string],
    genre: "Beat 'em up", tagline: "The final brawl at the pearly gates.",
    description: "Part 7 of the Hobo series: punch, kick, and gross-out special moves through heaven as the toughest hobo around. Original Flash game, every level included.",
    href: "/play/hobo-7", source: "/ports/flash/index.html?game=hobo-7", cta: "START BRAWLING",
    tone: "orange" as const, cover: "/hobo-7-cover-box-art.png", focus: "50% 40%", players: "1",
    download: "About 14 MB on first launch", creator: "Seethru Productions",
    notice: "Flash game played through the Ruffle emulator; some effects may differ from the original.",
    specs: [
      { label: "Game", value: "Flash game · Ruffle emulator" },
      { label: "Developer", value: "Seethru Productions" },
      { label: "Controls", value: "Arrow keys + A / S / D · see in-game help" },
      { label: "First download", value: "About 14 MB" },
    ],
    features: ["Full original game", "Gross-out special moves", "Full-screen player"],
  },
];
