// Web ports hosted by their own makers (from RadiantOpti's list, 9 Oct 2026). They run on the makers' sites inside our
// player, or in a new tab when the site refuses to be embedded. None can be downloaded: their files live on those
// servers and load as the game runs, so they need the internet. Each was opened and checked on 9 Oct 2026; the notes say
// what a player will meet (own game files, a browser check, a site that is down).
type Launch = "embed" | "tab";
type WebGame = {
  id: string; title: [string, string]; url: string; genre: string; tagline: string; description: string; cta: string;
  maker: string; original: string; controls: string; players: string; features: string[]; notice?: string; launch?: Launch; broken?: boolean;
};

const list: WebGame[] = [
  { id: "bo1-zombies", title: ["BLACK OPS", "ZOMBIES"], url: "https://vel.gg/bo1z", genre: "Zombies survival", tagline: "Hold the line. Round after round.",
    description: "The Black Ops zombies maps rebuilt for the browser: pick a map from the mission select, buy guns off the walls and survive as long as you can.",
    cta: "PICK A MAP", maker: "Fan web port · vel.gg", original: "Treyarch / Activision", controls: "Keyboard + mouse", players: "1",
    features: ["Mission select with every map", "Round-based survival", "Full-screen player"], notice: "Unofficial fan port. The first load takes about 20 seconds." },
  { id: "moon-zombies", title: ["ZOMBIES", "MOON"], url: "https://moon-zombies.pages.dev", genre: "Zombies survival", tagline: "Survive on the far side of the moon.",
    description: "The Moon map as a standalone browser game: low gravity, the excavators and endless rounds of the undead.",
    cta: "LAUNCH TO THE MOON", maker: "Fan web port · pages.dev", original: "Treyarch / Activision", controls: "Keyboard + mouse", players: "1",
    features: ["Solo survival", "Explore mode", "Full-screen player"], notice: "Unofficial fan port. The first load takes about 20 seconds." },
  { id: "kino-der-toten", title: ["ZOMBIES", "KINO DER TOTEN"], url: "https://kino-der-toten.pages.dev", genre: "Zombies survival", tagline: "The show must go on.",
    description: "The theatre map, rebuilt for the browser: open the doors, link the teleporter and hold out in the Kino.",
    cta: "ENTER THE THEATRE", maker: "Fan web port · pages.dev", original: "Treyarch / Activision", controls: "Keyboard + mouse", players: "1",
    features: ["Solo survival", "Classic theatre map", "Full-screen player"], notice: "Unofficial fan port. The first load takes about 20 seconds." },
  { id: "cheese-cube", title: ["BO3 ZOMBIES", "CHEESE CUBE"], url: "https://cheese-cube.pages.dev", genre: "Zombies survival", tagline: "A yellow box full of the undead.",
    description: "The Black Ops III custom map Cheese Cube in the browser, with its Unlimited, Cube of Circles and Tower of Cheddar variants.",
    cta: "ENTER THE CUBE", maker: "Fan web port · pages.dev", original: "Black Ops III custom map", controls: "Keyboard + mouse", players: "1",
    features: ["Three map variants", "Round-based survival", "Full-screen player"], notice: "Unofficial fan port." },
  { id: "vibe-slops", title: ["CLAUDE OF DUTY", "VIBE SLOPS II"], url: "https://vibeslops.luckeysystems.com/", genre: "Shooter parody", tagline: "Black Ops II, reimagined by vibes.",
    description: "Shared around as \"Black Ops 2\", this is a fan-made browser shooter inspired by it: a parody campaign built from scratch, not the original game.",
    cta: "START THE CAMPAIGN", maker: "luckeysystems", original: "Inspired by Black Ops II", controls: "Keyboard + mouse · touch", players: "1",
    features: ["Original fan game", "Campaign missions", "Full-screen player"], notice: "A fan parody, not Black Ops II itself." },
  { id: "mw2", title: ["MODERN", "WARFARE 2"], url: "https://ovz-game-production.up.railway.app/", genre: "Shooter", tagline: "Fan port of the 2009 classic.",
    description: "A browser build of Modern Warfare 2 hosted on Railway, played right here in the arcade's player.",
    cta: "OPEN MODERN WARFARE 2", maker: "Fan web port · Railway", original: "Infinity Ward / Activision", controls: "Keyboard + mouse", players: "1+",
    features: ["Online host", "Desktop recommended", "Full-screen player"],
    notice: "The host shows a \"Checking your browser\" page first (it is busy and sometimes turns visitors away): complete it, then the game loads." },
  { id: "skate-3", title: ["SKATE.", "3"], url: "https://skate.aaddpp.lol", genre: "Skateboarding", tagline: "Port of Port Carverton, in a tab.",
    description: "A fan project that runs Skate 3 in the browser. Nothing is hosted: you bring your own legally owned copy of the game and it is converted on your machine.",
    cta: "OPEN SKATE 3", maker: "Fan project · aaddpp", original: "EA Black Box", controls: "Keyboard · gamepad", players: "1",
    features: ["Bring your own game files", "Gamepad support", "Full-screen player"], notice: "Needs your own copy of Skate 3: the site converts your game files, it does not provide them." },
  { id: "skate-rust", title: ["SKATE", "RUST"], url: "https://global-terror.net", genre: "Skateboarding", tagline: "Street skating on global-terror.net.",
    description: "The skate game on global-terror.net. Its site does not allow being shown inside other sites, so it opens in its own tab.",
    cta: "OPEN SKATE RUST", maker: "global-terror.net", original: "global-terror.net", controls: "Keyboard · gamepad", players: "1",
    features: ["Opens in its own tab", "Online host", "Desktop recommended"], launch: "tab" },
  { id: "cs-surf", title: ["CS", "SURF"], url: "https://surfd.net", genre: "Movement", tagline: "Classic surf maps, right in the browser.",
    description: "Surfd brings Counter-Strike surf to the browser: 29 classic maps, records, a map browser and online servers.",
    cta: "HIT THE RAMPS", maker: "surfd.net", original: "Counter-Strike surf community", controls: "Keyboard + mouse", players: "1+",
    features: ["29 surf maps", "Online and solo", "Full-screen player"] },
  { id: "halo-ce", title: ["HALO", "COMBAT EVOLVED"], url: "https://mitchellhynes.com/halo", genre: "Shooter", tagline: "The original Halo, from your own disc.",
    description: "Halo: Combat Evolved running in the browser from the community decompilation. The site provides no game data: you choose an Xbox disc image (XISO) you own.",
    cta: "OPEN HALO", maker: "Mitchell Hynes", original: "Bungie / Microsoft", controls: "Keyboard + mouse · gamepad", players: "1",
    features: ["Bring your own disc image", "Gamepad support", "Full-screen player"], notice: "Needs your own Halo XISO (Xbox disc image); the site does not include the game." },
  { id: "halo-ce-mobile", title: ["HALO CE", "MOBILE"], url: "https://hcemobile.com/", genre: "Shooter", tagline: "Combat Evolved on your phone.",
    description: "A fan port of Halo: Combat Evolved built for phones and tablets, with touch controls. Its own site can also install it as an app that plays offline.",
    cta: "OPEN HALO CE MOBILE", maker: "Fan project · hcemobile.com", original: "Bungie / Microsoft", controls: "Touch · keyboard + mouse", players: "1",
    features: ["Touch controls", "Installs as its own app", "Full-screen player"], notice: "Follow its \"How to play\" steps the first time; it may ask for your own game files." },
  { id: "pes-6", title: ["PRO EVOLUTION", "SOCCER 6"], url: "https://pes6.optijuegos.net/", genre: "Football", tagline: "PES 6, online, in the browser.",
    description: "Pro Evolution Soccer 6 as a web port with online matches, relay servers and a camera mod. The site is in Spanish.",
    cta: "KICK OFF", maker: "OptiProjects", original: "Konami", controls: "Keyboard · gamepad", players: "1–2",
    features: ["Online matches", "Gamepad support", "Full-screen player"], notice: "The site is in Spanish." },
  { id: "gta-5", title: ["GRAND THEFT", "AUTO V"], url: "https://web.archive.org/web/20261006055917/https://playgta5.com/", genre: "Open world", tagline: "Archived copy: not working right now.",
    description: "An archived copy of playgta5.com. It stops at 1% with \"not cross-origin isolated\": the archive cannot serve the browser isolation the build needs, so it does not start, embedded or in its own tab.",
    cta: "TRY IT ANYWAY", maker: "Archived copy · web.archive.org", original: "Rockstar Games", controls: "Keyboard + mouse", players: "1",
    features: ["Archived page", "Does not start (checked 9 Oct 2026)"], broken: true,
    notice: "Not working: the archived build needs cross-origin isolation, which web.archive.org does not provide." },
  { id: "gta-vice-city", title: ["GTA", "VICE CITY"], url: "https://joncodeofficial.github.io/gta-vice-city-wasm", genre: "Open world", tagline: "Welcome to the 80s.",
    description: "Vice City running in WebAssembly. Import the game data once and it is kept in your browser, then plays fully offline from that site.",
    cta: "OPEN VICE CITY", maker: "joncodeofficial", original: "Rockstar Games", controls: "Keyboard + mouse · gamepad", players: "1",
    features: ["Import game data once", "Plays offline after import", "Full-screen player"], notice: "Asks for the game data (game.tar.gz) the first time." },
  { id: "simpsons-hit-and-run", title: ["THE SIMPSONS", "HIT & RUN"], url: "https://shar-wasm.cjoseph.workers.dev/?skipmovie", genre: "Open world", tagline: "Springfield, in WebAssembly.",
    description: "The Simpsons: Hit & Run compiled to WebAssembly: drive and run around Springfield with Homer, Bart, Lisa, Marge and Apu.",
    cta: "PRESS PLAY", maker: "cjoseph", original: "Radical Entertainment", controls: "Keyboard · gamepad", players: "1",
    features: ["Full story mode", "Gamepad support", "Full-screen player"] },
  { id: "quake", title: ["", "QUAKE"], url: "https://q1.pieter.com", genre: "Arena shooter", tagline: "QuakeWorld deathmatch, live.",
    description: "QuakeWorld multiplayer in the browser: type a name, press Play and drop straight into a live server.",
    cta: "JOIN THE MATCH", maker: "Pieter Levels (non-commercial)", original: "id Software", controls: "Keyboard + mouse", players: "Online",
    features: ["Live multiplayer", "No install", "Full-screen player"] },
  { id: "quake-2", title: ["QUAKE", "II"], url: "https://q2.pieter.com", genre: "Arena shooter", tagline: "Strogg-blasting deathmatch online.",
    description: "Quake II multiplayer in the browser: pick a name and join the live server.",
    cta: "JOIN THE MATCH", maker: "Pieter Levels (non-commercial)", original: "id Software", controls: "Keyboard + mouse", players: "Online",
    features: ["Live multiplayer", "No install", "Full-screen player"] },
  { id: "quake-3", title: ["QUAKE III", "ARENA"], url: "https://q3.pieter.com", genre: "Arena shooter", tagline: "The arena is open.",
    description: "Quake III Arena multiplayer in the browser: rocket jumps, rail guns and a live scoreboard.",
    cta: "JOIN THE MATCH", maker: "Pieter Levels (non-commercial)", original: "id Software", controls: "Keyboard + mouse", players: "Online",
    features: ["Live multiplayer", "No install", "Full-screen player"] },
  { id: "rtcw", title: ["RETURN TO CASTLE", "WOLFENSTEIN"], url: "https://rtcw.pieter.com", genre: "Team shooter", tagline: "Axis versus Allies, live.",
    description: "Return to Castle Wolfenstein multiplayer in the browser: objective maps like mp_beach with a live player list.",
    cta: "JOIN THE MATCH", maker: "Pieter Levels (non-commercial)", original: "Gray Matter / id Software", controls: "Keyboard + mouse", players: "Online",
    features: ["Live multiplayer", "Objective maps", "Full-screen player"] },
  { id: "urban-terror", title: ["URBAN", "TERROR"], url: "https://ut.pieter.com", genre: "Tactical shooter", tagline: "Fast tactical shooting, online.",
    description: "Listed as \"Unreal Tournament\", but ut.pieter.com is Urban Terror: the free tactical shooter, with live multiplayer in the browser.",
    cta: "JOIN THE MATCH", maker: "Pieter Levels (non-commercial)", original: "FrozenSand", controls: "Keyboard + mouse", players: "Online",
    features: ["Live multiplayer", "Free game", "Full-screen player"] },
  { id: "half-life", title: ["HALF-", "LIFE"], url: "https://pixelsuft.github.io/hl/", genre: "Shooter", tagline: "Black Mesa, by way of Xash3D.",
    description: "Half-Life on the Xash3D FWGS engine compiled for the browser: set the memory size, press Start.",
    cta: "BOOT BLACK MESA", maker: "pixelsuft", original: "Valve", controls: "Keyboard + mouse", players: "1",
    features: ["Xash3D engine", "Adjustable memory", "Full-screen player"], notice: "May ask for your own Half-Life game files." },
  { id: "webxash", title: ["HALF-LIFE", "& CS 1.6"], url: "https://x8bitrain.github.io/webXash/", genre: "Shooter", tagline: "Free demos built in, or your own files.",
    description: "WebXash runs Half-Life and Counter-Strike 1.6 in the browser. The official free Half-Life demos (Uplink, Day One, Hazard Course) play straight away; the full games use your own files.",
    cta: "OPEN WEBXASH", maker: "x8bitrain", original: "Valve", controls: "Keyboard + mouse", players: "1",
    features: ["Free official demos", "Counter-Strike 1.6 with your files", "Saves in the browser"] },
  { id: "diablo", title: ["", "DIABLO"], url: "https://johnimril.github.io/diablo_web/", genre: "Action RPG", tagline: "Stay a while and listen.",
    description: "The original Diablo in the browser. The free shareware demo plays right away (25–50 MB); load your own DIABDAT.MPQ for the full game.",
    cta: "ENTER TRISTRAM", maker: "Nikita Malyshev (diablo_web)", original: "Blizzard North", controls: "Mouse · keyboard", players: "1",
    features: ["Free shareware demo", "Full game with your MPQ", "Full-screen player"] },
  { id: "hedgewars", title: ["", "HEDGEWARS"], url: "https://webwars.link", genre: "Turn-based artillery", tagline: "Hedgehogs at war.",
    description: "Hedgewars, the free and open-source artillery game, in the browser. Right now the site's security certificate is broken, so browsers block it.",
    cta: "TRY IT ANYWAY", maker: "webwars.link", original: "Hedgewars project (open source)", controls: "Keyboard + mouse", players: "1–8",
    features: ["Open-source game", "Site currently down (checked 9 Oct 2026)"], broken: true,
    notice: "Not working right now: webwars.link has an invalid security certificate, so browsers refuse to open it." },
  { id: "wasm-arcade", title: ["WASM", "ARCADE"], url: "https://wasmarcade.com/", genre: "Game collection", tagline: "More GTA, Minecraft and Flash ports.",
    description: "A whole arcade of WebAssembly ports: more GTA, Minecraft and classic Flash games. It opens in its own tab because the site does not allow being embedded.",
    cta: "OPEN WASM ARCADE", maker: "wasmarcade.com", original: "Various", controls: "Keyboard + mouse", players: "1",
    features: ["Dozens of ports", "Opens in its own tab"], launch: "tab", notice: "Some ports there need your own game files. Skip anything that asks you to download a launcher." },
];

export const webGames = list.map((game, index) => {
  const host = new URL(game.url).host.replace(/^www\./, "");
  return {
    id: game.id, number: String(29 + index), name: game.title, genre: game.genre, tagline: game.tagline, description: game.description,
    href: `/play/${game.id}`, source: game.url, cta: game.cta,
    tone: (index % 2 ? "teal" : "orange") as "teal" | "orange", cover: `/${game.id}-cover-box-art.png`, focus: "50% 40%", players: game.players,
    download: `Online only · runs on ${host}`, creator: game.maker, notice: game.notice,
    launch: game.launch ?? "embed", broken: !!game.broken, host,
    specs: [
      { label: "Game", value: game.launch === "tab" ? `Web port · opens on ${host}` : `Web port · hosted on ${host}` },
      { label: "Original", value: game.original },
      { label: "Controls", value: game.controls },
      { label: "Download", value: "Online only · not downloadable" },
    ],
    features: game.features,
  };
});
